name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint and capture score
      run: |
        pylint $(git ls-files '*.py') --exit-zero --output-format=text > pylint_report.txt

    - name: Fail if score is less than 9.5
      run: |
        SCORE=$(grep 'Your code has been rated at' pylint_report.txt | awk '{print $7}' | cut -d'/' -f1)
        echo "Pylint score: $SCORE"
        MIN_SCORE=9.5
        # Convert to float comparison
        python -c "import sys; exit(0) if float('$SCORE') >= $MIN_SCORE else sys.exit(1)"
